name: frontend

on:
  workflow_dispatch:
  push:
    paths:
      - frontend/**
      - .github/workflows/frontend.yml
  pull_request:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/frontend.yml


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies from lock.
        run: npm ci
        working-directory: ./frontend

      # - name: Linter.
      #   run: npm run lint:ci

      # - name: Unit tests.
      #   run: npm run test:cov

      # - name: E2E tests.
      #   run: npm run test:e2e

      - name: Build source code.
        run: npm run build
        working-directory: ./frontend

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          accountId: 620ff29bbd515d2848f5306578bd1d1d
          projectName: airdrop
          directory: frontend/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
